# Generated by Django 6.0.6 on 2026-06-03 13:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('buildings', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('source_type', models.CharField(choices=[('receipt', 'Receipt'), ('expense', 'Expense')], max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_entries', to='buildings.building')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbook_entries', to='accounts.organisation')),
            ],
            options={
                'ordering': ['entry_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('entry_type', models.CharField(choices=[('charge', 'Charge'), ('payment', 'Payment'), ('opening', 'Opening Balance'), ('adjustment', 'Adjustment')], max_length=20)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('running_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='buildings.building')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='tenants.tenant')),
            ],
            options={
                'ordering': ['entry_date', 'created_at'],
            },
        ),
    ]
