# Generated by Django 6.0.6 on 2026-06-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookentry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
