# Generated by Django 6.0.6 on 2026-06-04 13:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_standard_rate'),
        ('expenses', '0002_supplier_and_paid_amount'),
        ('finance', '0002_add_ip_audit_trail'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='account_type',
            field=models.CharField(choices=[('debtor', 'Debtor (Tenant)'), ('creditor', 'Creditor (Supplier)'), ('revenue', 'Revenue'), ('expense', 'Expense')], default='debtor', max_length=10),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='period_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='period_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='expenses.supplier'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('charge', 'Rent Charge'), ('payment', 'Payment'), ('opening', 'Opening Balance'), ('adjustment', 'Adjustment'), ('accrual', 'Accrual'), ('reversal', 'Reversal')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='MonthlyAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveSmallIntegerField()),
                ('period_year', models.PositiveSmallIntegerField()),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('settled', 'Settled')], default='unpaid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.ledgerentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_accruals', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('tenant', 'period_month', 'period_year')},
            },
        ),
    ]
