# Generated by Django 6.0.6 on 2026-06-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxsetting',
            name='tax_type',
            field=models.CharField(choices=[('receipt', 'Transaction Tax (deducted on receipt)'), ('income', 'Income Tax (applied on P&L)')], default='receipt', max_length=10),
        ),
    ]
