# Generated by Django 6.0.6 on 2026-06-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='period_month',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='period_year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
