# Generated by Django 6.0.6 on 2026-06-03 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('op_manager', 'Operational Manager'), ('property_manager', 'Property Manager'), ('cashier_receipts', 'Cashier – Receipts'), ('cashier_expenses', 'Cashier – Expenses'), ('accountant', 'Accountant')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
