# Generated by Django 6.0.6 on 2026-06-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='standard_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default monthly rent per room for this building (UGX)', max_digits=15, null=True),
        ),
    ]
